### ISSUE TITLE
 It would be great if this mod had an automatic save function! Save every X minutes, up to X times, and you can set this x yourself!

### ISSUE THREAD

**Issue by moonboss666** [Rashnain/SaveMod#15] opened 2024-07-08 11:51 UTC
It would be great if this mod had an automatic save function! Save every X minutes, up to X times, and you can set this x yourself!

**Comment by Rashnain** [comment] 2024-08-09 21:54
Duplicate of #7.

**Closed by Rashnain** 2024-08-09 21:54 UTC
